# Generated by Django 3.1 on 2020-08-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30, unique=True)),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('deceased', models.IntegerField()),
            ],
        ),
    ]
