# Generated by Django 3.1 on 2020-08-30 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateInfo',
        ),
    ]
